### ISSUE TITLE
/mw manage Crash

### ISSUE THREAD

**Issue by DragonfireHD** [CzechPMDevs/MultiWorld#248] opened 2021-12-17 21:45 UTC
- Issue Description:
If i use /mw manage Server crashed

- Version: 1.7.0-beta4

- Server Version: 8.0.13/ version 1.18.0 

- Crashdump, backtrace or other files:
Error: Class "czechpmdevs\libpmform\type\SimpleForm" not found
File: plugins/MultiWorld.4.0.phar/src/czechpmdevs/multiworld/command/subcommand/ManageSubCommand
Line: 56
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MultiWorld

Code:

Backtrace:
#0 plugins/MultiWorld.4.0.phar/src/czechpmdevs/multiworld/command/MultiWorldCommand(98): czechpmdevs\multiworld\command\subcommand\ManageSubCommand->execute(object ipad54\netherblocks\player\Player#96246, array[0], string[6] manage)
#1 pmsrc/src/command/SimpleCommandMap(220): czechpmdevs\multiworld\command\MultiWorldCommand->execute(object ipad54\netherblocks\player\Player#96246, string[2] mw, array[0])
#2 pmsrc/src/Server(1406): pocketmine\command\SimpleCommandMap->dispatch(object ipad54\netherblocks\player\Player#96246, string[9] mw manage)
#3 pmsrc/src/player/Player(1337): pocketmine\Server->dispatchCommand(object ipad54\netherblocks\player\Player#96246, string[9] mw manage)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(688): pocketmine\player\Player->chat(string[10] /mw manage)
#5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(60): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#134161)
#6

**Comment by VixikHD** [comment] 2021-12-17 21:49
Where can I get the plugin version to reproduce the error?

**Comment by DragonfireHD** [comment] 2021-12-18 00:09
The error comes i dont now where the error comes i see just a Crashdump i change nothing 🤔

**Comment by VixikHD** [comment] 2021-12-23 21:03
I'm closing this since I cannot reproduce the bug with Poggit built versions of plugins. Seems like you've tried to load plugin with devtools without virion.

**Closed by VixikHD** 2021-12-23 21:03 UTC
